debug: true

spring:
  application:
    name: spring-boot-webflux
  main:
    allow-bean-definition-overriding: true

server:
  monitoring:
    recipients: dltkd1214@naver.com
  port: 8383
  master:
    url: http://127.0.0.1:8383
